kind: ReplicationController
apiVersion: v1
metadata:
  name: guestbook-go
  labels:
    app: guestbook-go
spec:
  replicas: 3
  selector:
    app: guestbook-go
  template:
    metadata:
      labels:
        app: guestbook-go
    spec:
      containers:
      - name: guestbook-go
        image: k8s.gcr.io/guestbook:v3
        ports:
        - name: http-server
          containerPort: 3000
